// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var part2 = "world";

if (part2 === "world") {
  part2 = "adam";
}

var message = "hello " + part2;

console.log(message);

exports.message = message;
/*  Not a pure module */
